# This is a basic workflow to help you get started with Actions

name: Pull Request Check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the v2 branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run type check
      run: yarn type

    - name: Run ESLint
      run: yarn lint

    - name: Run build
      run: yarn build

    - name: Log
      run: echo Check complete.
