name: Pull Request Check
on:
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.12
          run_install: true
      - name: Type check
        run: pnpm run type
      - name: ESLint check
        run: pnpm run lint-check
      - name: Build core
        run: pnpm run build-core
      - name: Build features
        run: |
          cd registry
          pnpm install
          cd ../
          pnpm run build-features
      - name: Log
        run: echo Check complete.
